name: GCP Auth Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/491439791457/locations/global/workloadIdentityPools/ci-pool-github-actions/providers/github"
        service_account: "github-action-xpert-forex-trad@xpert-forex-trade.iam.gserviceaccount.com"

    - name: Verify identity
      run: |
        gcloud auth list
